# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import vigilio_pb2 as vigilio__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in vigilio_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VigilioServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetFundTypes = channel.unary_unary(
                '/vigilio.VigilioService/GetFundTypes',
                request_serializer=vigilio__pb2.GetFundTypesRequest.SerializeToString,
                response_deserializer=vigilio__pb2.GetFundTypesResponse.FromString,
                _registered_method=True)
        self.ListShareHolders = channel.unary_unary(
                '/vigilio.VigilioService/ListShareHolders',
                request_serializer=vigilio__pb2.ShareHolderListRequest.SerializeToString,
                response_deserializer=vigilio__pb2.ShareHolderListResponse.FromString,
                _registered_method=True)
        self.ShareHoldersSummary = channel.unary_unary(
                '/vigilio.VigilioService/ShareHoldersSummary',
                request_serializer=vigilio__pb2.ShareHolderSummaryListRequest.SerializeToString,
                response_deserializer=vigilio__pb2.ShareHolderSummaryListResponse.FromString,
                _registered_method=True)
        self.GetShareHolderForDate = channel.unary_unary(
                '/vigilio.VigilioService/GetShareHolderForDate',
                request_serializer=vigilio__pb2.ShareHolderForDateRequest.SerializeToString,
                response_deserializer=vigilio__pb2.ShareHolderForDateResponse.FromString,
                _registered_method=True)
        self.ExportShareHoldersSummaryExcel = channel.unary_unary(
                '/vigilio.VigilioService/ExportShareHoldersSummaryExcel',
                request_serializer=vigilio__pb2.ShareHolderSummaryExportRequest.SerializeToString,
                response_deserializer=vigilio__pb2.ShareHolderSummaryExportResponse.FromString,
                _registered_method=True)
        self.GetShareHolderDetail = channel.unary_unary(
                '/vigilio.VigilioService/GetShareHolderDetail',
                request_serializer=vigilio__pb2.GetShareHolderDetailRequest.SerializeToString,
                response_deserializer=vigilio__pb2.GetShareHolderDetailResponse.FromString,
                _registered_method=True)
        self.ExportShareHolderExcel = channel.unary_unary(
                '/vigilio.VigilioService/ExportShareHolderExcel',
                request_serializer=vigilio__pb2.ExportShareHolderExcelRequest.SerializeToString,
                response_deserializer=vigilio__pb2.ExportShareHolderExcelResponse.FromString,
                _registered_method=True)


class VigilioServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetFundTypes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListShareHolders(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShareHoldersSummary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetShareHolderForDate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExportShareHoldersSummaryExcel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetShareHolderDetail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExportShareHolderExcel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VigilioServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetFundTypes': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFundTypes,
                    request_deserializer=vigilio__pb2.GetFundTypesRequest.FromString,
                    response_serializer=vigilio__pb2.GetFundTypesResponse.SerializeToString,
            ),
            'ListShareHolders': grpc.unary_unary_rpc_method_handler(
                    servicer.ListShareHolders,
                    request_deserializer=vigilio__pb2.ShareHolderListRequest.FromString,
                    response_serializer=vigilio__pb2.ShareHolderListResponse.SerializeToString,
            ),
            'ShareHoldersSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.ShareHoldersSummary,
                    request_deserializer=vigilio__pb2.ShareHolderSummaryListRequest.FromString,
                    response_serializer=vigilio__pb2.ShareHolderSummaryListResponse.SerializeToString,
            ),
            'GetShareHolderForDate': grpc.unary_unary_rpc_method_handler(
                    servicer.GetShareHolderForDate,
                    request_deserializer=vigilio__pb2.ShareHolderForDateRequest.FromString,
                    response_serializer=vigilio__pb2.ShareHolderForDateResponse.SerializeToString,
            ),
            'ExportShareHoldersSummaryExcel': grpc.unary_unary_rpc_method_handler(
                    servicer.ExportShareHoldersSummaryExcel,
                    request_deserializer=vigilio__pb2.ShareHolderSummaryExportRequest.FromString,
                    response_serializer=vigilio__pb2.ShareHolderSummaryExportResponse.SerializeToString,
            ),
            'GetShareHolderDetail': grpc.unary_unary_rpc_method_handler(
                    servicer.GetShareHolderDetail,
                    request_deserializer=vigilio__pb2.GetShareHolderDetailRequest.FromString,
                    response_serializer=vigilio__pb2.GetShareHolderDetailResponse.SerializeToString,
            ),
            'ExportShareHolderExcel': grpc.unary_unary_rpc_method_handler(
                    servicer.ExportShareHolderExcel,
                    request_deserializer=vigilio__pb2.ExportShareHolderExcelRequest.FromString,
                    response_serializer=vigilio__pb2.ExportShareHolderExcelResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vigilio.VigilioService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vigilio.VigilioService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VigilioService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetFundTypes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vigilio.VigilioService/GetFundTypes',
            vigilio__pb2.GetFundTypesRequest.SerializeToString,
            vigilio__pb2.GetFundTypesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListShareHolders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vigilio.VigilioService/ListShareHolders',
            vigilio__pb2.ShareHolderListRequest.SerializeToString,
            vigilio__pb2.ShareHolderListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ShareHoldersSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vigilio.VigilioService/ShareHoldersSummary',
            vigilio__pb2.ShareHolderSummaryListRequest.SerializeToString,
            vigilio__pb2.ShareHolderSummaryListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetShareHolderForDate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vigilio.VigilioService/GetShareHolderForDate',
            vigilio__pb2.ShareHolderForDateRequest.SerializeToString,
            vigilio__pb2.ShareHolderForDateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExportShareHoldersSummaryExcel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vigilio.VigilioService/ExportShareHoldersSummaryExcel',
            vigilio__pb2.ShareHolderSummaryExportRequest.SerializeToString,
            vigilio__pb2.ShareHolderSummaryExportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetShareHolderDetail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vigilio.VigilioService/GetShareHolderDetail',
            vigilio__pb2.GetShareHolderDetailRequest.SerializeToString,
            vigilio__pb2.GetShareHolderDetailResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExportShareHolderExcel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vigilio.VigilioService/ExportShareHolderExcel',
            vigilio__pb2.ExportShareHolderExcelRequest.SerializeToString,
            vigilio__pb2.ExportShareHolderExcelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
