# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import vigilio_pb2 as vigilio__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in vigilio_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VigilioServiceStub(object):
    """-----------------------------
    Service definition
    -----------------------------
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetShareHolderSummary = channel.unary_unary(
                '/vigilio.VigilioService/GetShareHolderSummary',
                request_serializer=vigilio__pb2.ShareHolderSummaryRequest.SerializeToString,
                response_deserializer=vigilio__pb2.ShareHolderSummaryResponse.FromString,
                _registered_method=True)
        self.GetShareHolderDetail = channel.unary_unary(
                '/vigilio.VigilioService/GetShareHolderDetail',
                request_serializer=vigilio__pb2.ShareHolderDetailRequest.SerializeToString,
                response_deserializer=vigilio__pb2.ShareHolderDetailResponse.FromString,
                _registered_method=True)
        self.GetFundTypes = channel.unary_unary(
                '/vigilio.VigilioService/GetFundTypes',
                request_serializer=vigilio__pb2.GetFundTypesRequest.SerializeToString,
                response_deserializer=vigilio__pb2.GetFundTypesResponse.FromString,
                _registered_method=True)


class VigilioServiceServicer(object):
    """-----------------------------
    Service definition
    -----------------------------
    """

    def GetShareHolderSummary(self, request, context):
        """Shareholder endpoints
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetShareHolderDetail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFundTypes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VigilioServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetShareHolderSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.GetShareHolderSummary,
                    request_deserializer=vigilio__pb2.ShareHolderSummaryRequest.FromString,
                    response_serializer=vigilio__pb2.ShareHolderSummaryResponse.SerializeToString,
            ),
            'GetShareHolderDetail': grpc.unary_unary_rpc_method_handler(
                    servicer.GetShareHolderDetail,
                    request_deserializer=vigilio__pb2.ShareHolderDetailRequest.FromString,
                    response_serializer=vigilio__pb2.ShareHolderDetailResponse.SerializeToString,
            ),
            'GetFundTypes': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFundTypes,
                    request_deserializer=vigilio__pb2.GetFundTypesRequest.FromString,
                    response_serializer=vigilio__pb2.GetFundTypesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vigilio.VigilioService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vigilio.VigilioService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VigilioService(object):
    """-----------------------------
    Service definition
    -----------------------------
    """

    @staticmethod
    def GetShareHolderSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vigilio.VigilioService/GetShareHolderSummary',
            vigilio__pb2.ShareHolderSummaryRequest.SerializeToString,
            vigilio__pb2.ShareHolderSummaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetShareHolderDetail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vigilio.VigilioService/GetShareHolderDetail',
            vigilio__pb2.ShareHolderDetailRequest.SerializeToString,
            vigilio__pb2.ShareHolderDetailResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFundTypes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vigilio.VigilioService/GetFundTypes',
            vigilio__pb2.GetFundTypesRequest.SerializeToString,
            vigilio__pb2.GetFundTypesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
