# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import vigilio_pb2 as vigilio__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in vigilio_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VigilioServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetFundTypes = channel.unary_unary(
                '/vigilio.VigilioService/GetFundTypes',
                request_serializer=vigilio__pb2.GetFundTypesRequest.SerializeToString,
                response_deserializer=vigilio__pb2.GetFundTypesResponse.FromString,
                _registered_method=True)
        self.ListShareHolders = channel.unary_unary(
                '/vigilio.VigilioService/ListShareHolders',
                request_serializer=vigilio__pb2.ShareHolderListRequest.SerializeToString,
                response_deserializer=vigilio__pb2.ShareHolderListResponse.FromString,
                _registered_method=True)
        self.ShareHoldersSummary = channel.unary_unary(
                '/vigilio.VigilioService/ShareHoldersSummary',
                request_serializer=vigilio__pb2.ShareHolderSummaryListRequest.SerializeToString,
                response_deserializer=vigilio__pb2.ShareHolderSummaryListResponse.FromString,
                _registered_method=True)
        self.GetShareHolderForDate = channel.unary_unary(
                '/vigilio.VigilioService/GetShareHolderForDate',
                request_serializer=vigilio__pb2.ShareHolderForDateRequest.SerializeToString,
                response_deserializer=vigilio__pb2.ShareHolderForDateResponse.FromString,
                _registered_method=True)
        self.ExportShareHoldersSummaryExcel = channel.unary_unary(
                '/vigilio.VigilioService/ExportShareHoldersSummaryExcel',
                request_serializer=vigilio__pb2.ShareHolderSummaryExportRequest.SerializeToString,
                response_deserializer=vigilio__pb2.ShareHolderSummaryExportResponse.FromString,
                _registered_method=True)
        self.GetShareHolderDetail = channel.unary_unary(
                '/vigilio.VigilioService/GetShareHolderDetail',
                request_serializer=vigilio__pb2.GetShareHolderDetailRequest.SerializeToString,
                response_deserializer=vigilio__pb2.GetShareHolderDetailResponse.FromString,
                _registered_method=True)
        self.ExportShareHolderExcel = channel.unary_unary(
                '/vigilio.VigilioService/ExportShareHolderExcel',
                request_serializer=vigilio__pb2.ExportShareHolderExcelRequest.SerializeToString,
                response_deserializer=vigilio__pb2.ExportShareHolderExcelResponse.FromString,
                _registered_method=True)
        self.ListCashFlows = channel.unary_unary(
                '/vigilio.VigilioService/ListCashFlows',
                request_serializer=vigilio__pb2.ListCashFlowsRequest.SerializeToString,
                response_deserializer=vigilio__pb2.ListCashFlowsResponse.FromString,
                _registered_method=True)
        self.GetCashFlowDetail = channel.unary_unary(
                '/vigilio.VigilioService/GetCashFlowDetail',
                request_serializer=vigilio__pb2.GetCashFlowDetailRequest.SerializeToString,
                response_deserializer=vigilio__pb2.GetCashFlowDetailResponse.FromString,
                _registered_method=True)
        self.ListTotalReturns = channel.unary_unary(
                '/vigilio.VigilioService/ListTotalReturns',
                request_serializer=vigilio__pb2.ListTotalReturnsRequest.SerializeToString,
                response_deserializer=vigilio__pb2.ListTotalReturnsResponse.FromString,
                _registered_method=True)
        self.ListEtfReturns = channel.unary_unary(
                '/vigilio.VigilioService/ListEtfReturns',
                request_serializer=vigilio__pb2.ListEtfReturnsRequest.SerializeToString,
                response_deserializer=vigilio__pb2.ListEtfReturnsResponse.FromString,
                _registered_method=True)
        self.GetNavTrend = channel.unary_unary(
                '/vigilio.VigilioService/GetNavTrend',
                request_serializer=vigilio__pb2.GetNavTrendRequest.SerializeToString,
                response_deserializer=vigilio__pb2.GetNavTrendResponse.FromString,
                _registered_method=True)
        self.GetSplits = channel.unary_unary(
                '/vigilio.VigilioService/GetSplits',
                request_serializer=vigilio__pb2.GetSplitsRequest.SerializeToString,
                response_deserializer=vigilio__pb2.GetSplitsResponse.FromString,
                _registered_method=True)
        self.GetProfits = channel.unary_unary(
                '/vigilio.VigilioService/GetProfits',
                request_serializer=vigilio__pb2.GetProfitsRequest.SerializeToString,
                response_deserializer=vigilio__pb2.GetProfitsResponse.FromString,
                _registered_method=True)
        self.GetPrices = channel.unary_unary(
                '/vigilio.VigilioService/GetPrices',
                request_serializer=vigilio__pb2.GetPricesRequest.SerializeToString,
                response_deserializer=vigilio__pb2.GetPricesResponse.FromString,
                _registered_method=True)


class VigilioServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetFundTypes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListShareHolders(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShareHoldersSummary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetShareHolderForDate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExportShareHoldersSummaryExcel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetShareHolderDetail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExportShareHolderExcel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCashFlows(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCashFlowDetail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTotalReturns(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListEtfReturns(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNavTrend(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSplits(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProfits(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPrices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VigilioServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetFundTypes': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFundTypes,
                    request_deserializer=vigilio__pb2.GetFundTypesRequest.FromString,
                    response_serializer=vigilio__pb2.GetFundTypesResponse.SerializeToString,
            ),
            'ListShareHolders': grpc.unary_unary_rpc_method_handler(
                    servicer.ListShareHolders,
                    request_deserializer=vigilio__pb2.ShareHolderListRequest.FromString,
                    response_serializer=vigilio__pb2.ShareHolderListResponse.SerializeToString,
            ),
            'ShareHoldersSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.ShareHoldersSummary,
                    request_deserializer=vigilio__pb2.ShareHolderSummaryListRequest.FromString,
                    response_serializer=vigilio__pb2.ShareHolderSummaryListResponse.SerializeToString,
            ),
            'GetShareHolderForDate': grpc.unary_unary_rpc_method_handler(
                    servicer.GetShareHolderForDate,
                    request_deserializer=vigilio__pb2.ShareHolderForDateRequest.FromString,
                    response_serializer=vigilio__pb2.ShareHolderForDateResponse.SerializeToString,
            ),
            'ExportShareHoldersSummaryExcel': grpc.unary_unary_rpc_method_handler(
                    servicer.ExportShareHoldersSummaryExcel,
                    request_deserializer=vigilio__pb2.ShareHolderSummaryExportRequest.FromString,
                    response_serializer=vigilio__pb2.ShareHolderSummaryExportResponse.SerializeToString,
            ),
            'GetShareHolderDetail': grpc.unary_unary_rpc_method_handler(
                    servicer.GetShareHolderDetail,
                    request_deserializer=vigilio__pb2.GetShareHolderDetailRequest.FromString,
                    response_serializer=vigilio__pb2.GetShareHolderDetailResponse.SerializeToString,
            ),
            'ExportShareHolderExcel': grpc.unary_unary_rpc_method_handler(
                    servicer.ExportShareHolderExcel,
                    request_deserializer=vigilio__pb2.ExportShareHolderExcelRequest.FromString,
                    response_serializer=vigilio__pb2.ExportShareHolderExcelResponse.SerializeToString,
            ),
            'ListCashFlows': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCashFlows,
                    request_deserializer=vigilio__pb2.ListCashFlowsRequest.FromString,
                    response_serializer=vigilio__pb2.ListCashFlowsResponse.SerializeToString,
            ),
            'GetCashFlowDetail': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCashFlowDetail,
                    request_deserializer=vigilio__pb2.GetCashFlowDetailRequest.FromString,
                    response_serializer=vigilio__pb2.GetCashFlowDetailResponse.SerializeToString,
            ),
            'ListTotalReturns': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTotalReturns,
                    request_deserializer=vigilio__pb2.ListTotalReturnsRequest.FromString,
                    response_serializer=vigilio__pb2.ListTotalReturnsResponse.SerializeToString,
            ),
            'ListEtfReturns': grpc.unary_unary_rpc_method_handler(
                    servicer.ListEtfReturns,
                    request_deserializer=vigilio__pb2.ListEtfReturnsRequest.FromString,
                    response_serializer=vigilio__pb2.ListEtfReturnsResponse.SerializeToString,
            ),
            'GetNavTrend': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNavTrend,
                    request_deserializer=vigilio__pb2.GetNavTrendRequest.FromString,
                    response_serializer=vigilio__pb2.GetNavTrendResponse.SerializeToString,
            ),
            'GetSplits': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSplits,
                    request_deserializer=vigilio__pb2.GetSplitsRequest.FromString,
                    response_serializer=vigilio__pb2.GetSplitsResponse.SerializeToString,
            ),
            'GetProfits': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProfits,
                    request_deserializer=vigilio__pb2.GetProfitsRequest.FromString,
                    response_serializer=vigilio__pb2.GetProfitsResponse.SerializeToString,
            ),
            'GetPrices': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPrices,
                    request_deserializer=vigilio__pb2.GetPricesRequest.FromString,
                    response_serializer=vigilio__pb2.GetPricesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vigilio.VigilioService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vigilio.VigilioService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VigilioService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetFundTypes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vigilio.VigilioService/GetFundTypes',
            vigilio__pb2.GetFundTypesRequest.SerializeToString,
            vigilio__pb2.GetFundTypesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListShareHolders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vigilio.VigilioService/ListShareHolders',
            vigilio__pb2.ShareHolderListRequest.SerializeToString,
            vigilio__pb2.ShareHolderListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ShareHoldersSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vigilio.VigilioService/ShareHoldersSummary',
            vigilio__pb2.ShareHolderSummaryListRequest.SerializeToString,
            vigilio__pb2.ShareHolderSummaryListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetShareHolderForDate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vigilio.VigilioService/GetShareHolderForDate',
            vigilio__pb2.ShareHolderForDateRequest.SerializeToString,
            vigilio__pb2.ShareHolderForDateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExportShareHoldersSummaryExcel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vigilio.VigilioService/ExportShareHoldersSummaryExcel',
            vigilio__pb2.ShareHolderSummaryExportRequest.SerializeToString,
            vigilio__pb2.ShareHolderSummaryExportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetShareHolderDetail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vigilio.VigilioService/GetShareHolderDetail',
            vigilio__pb2.GetShareHolderDetailRequest.SerializeToString,
            vigilio__pb2.GetShareHolderDetailResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExportShareHolderExcel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vigilio.VigilioService/ExportShareHolderExcel',
            vigilio__pb2.ExportShareHolderExcelRequest.SerializeToString,
            vigilio__pb2.ExportShareHolderExcelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListCashFlows(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vigilio.VigilioService/ListCashFlows',
            vigilio__pb2.ListCashFlowsRequest.SerializeToString,
            vigilio__pb2.ListCashFlowsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCashFlowDetail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vigilio.VigilioService/GetCashFlowDetail',
            vigilio__pb2.GetCashFlowDetailRequest.SerializeToString,
            vigilio__pb2.GetCashFlowDetailResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTotalReturns(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vigilio.VigilioService/ListTotalReturns',
            vigilio__pb2.ListTotalReturnsRequest.SerializeToString,
            vigilio__pb2.ListTotalReturnsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListEtfReturns(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vigilio.VigilioService/ListEtfReturns',
            vigilio__pb2.ListEtfReturnsRequest.SerializeToString,
            vigilio__pb2.ListEtfReturnsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNavTrend(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vigilio.VigilioService/GetNavTrend',
            vigilio__pb2.GetNavTrendRequest.SerializeToString,
            vigilio__pb2.GetNavTrendResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSplits(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vigilio.VigilioService/GetSplits',
            vigilio__pb2.GetSplitsRequest.SerializeToString,
            vigilio__pb2.GetSplitsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProfits(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vigilio.VigilioService/GetProfits',
            vigilio__pb2.GetProfitsRequest.SerializeToString,
            vigilio__pb2.GetProfitsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPrices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vigilio.VigilioService/GetPrices',
            vigilio__pb2.GetPricesRequest.SerializeToString,
            vigilio__pb2.GetPricesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
